# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scaleC <- function(X) {
    .Call('Coxnet_scaleC', PACKAGE = 'Coxnet', X)
}

OmegaC <- function(Omega, sgn) {
    .Call('Coxnet_OmegaC', PACKAGE = 'Coxnet', Omega, sgn)
}

OmegaSC <- function(OmegaS, sgn) {
    .Call('Coxnet_OmegaSC', PACKAGE = 'Coxnet', OmegaS, sgn)
}

max_lambdaC <- function(X, tevent, N, nevent, nevent1, loc1, n, alpha, wbeta, N0) {
    .Call('Coxnet_max_lambdaC', PACKAGE = 'Coxnet', X, tevent, N, nevent, nevent1, loc1, n, alpha, wbeta, N0)
}

pletaCm <- function(xb, exb, nevent, nevent1, loc1, n, ifast, itwo) {
    .Call('Coxnet_pletaCm', PACKAGE = 'Coxnet', xb, exb, nevent, nevent1, loc1, n, ifast, itwo)
}

cvtrimC <- function(beta, nn, nn2, loco, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo) {
    .Call('Coxnet_cvtrimC', PACKAGE = 'Coxnet', beta, nn, nn2, loco, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo)
}

coxenetC <- function(X, tevent, alpha, lambda, nlambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast) {
    .Call('Coxnet_coxenetC', PACKAGE = 'Coxnet', X, tevent, alpha, lambda, nlambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast)
}

cvcoxenetC <- function(X, tevent, alpha, lambda, nlambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF) {
    .Call('Coxnet_cvcoxenetC', PACKAGE = 'Coxnet', X, tevent, alpha, lambda, nlambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF)
}

coxnetC <- function(X, tevent, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast) {
    .Call('Coxnet_coxnetC', PACKAGE = 'Coxnet', X, tevent, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast)
}

cvcoxnetC <- function(X, tevent, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF) {
    .Call('Coxnet_cvcoxnetC', PACKAGE = 'Coxnet', X, tevent, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('Coxnet_RcppExport_registerCCallable', PACKAGE = 'Coxnet')
})
